add_newline = false

format = """
[](#7aa2f7)$username$hostname[](fg:#7aa2f7 bg:#2f3549)$directory[](fg:#2f3549 bg:#24283b)$git_branch$git_status[](fg:#24283b)$line_break$character
"""

[username]
show_always = false
format = "[ $user ]($style)"
style_user = "bg:#7aa2f7 fg:#1a1b26"
style_root = "bg:#7aa2f7 fg:#f7768e"

[hostname]
ssh_only = true
format = "[ $hostname ]($style)"
style = "bg:#7aa2f7 fg:#1a1b26"

[directory]
style = "bg:#2f3549 fg:#c0caf5"
format = "[ $path ]($style)"
truncate_to_repo = false
truncation_length = 4
truncation_symbol = "…/"

[git_branch]
symbol = ""
style = "bg:#24283b fg:#9ece6a"
format = "[ $symbol $branch ]($style)"

[git_status]
style = "bg:#24283b fg:#e0af68"
format = "[($all_status$ahead_behind )]($style)"

[character]
success_symbol = "[❯](bold #9ece6a)"
error_symbol = "[❯](bold #f7768e)"
vimcmd_symbol = "[❮](bold #7dcfff)"

[time]
disabled = true
