isWork: false
workDotfilesRepo: ""
workDotfilesPath: ".config/work-dotfiles"

ohMyZshRepo: "https://github.com/ohmyzsh/ohmyzsh.git"
ohMyZshPath: ".oh-my-zsh"
zshCustomPath: ".config/oh-my-zsh/custom"
zshTheme: "agnoster"

zshPlugins:
  - git
  - docker
  - docker-compose
  - z

workZshPlugins: []

opencodeEnabled: false
opencodeRepo: ""
opencodePath: ".config/opencode"
