isWork: false
workDotfilesRepo: ""
workDotfilesPath: ".config/work-dotfiles"

ohMyZshRepo: "https://github.com/ohmyzsh/ohmyzsh.git"
ohMyZshPath: ".oh-my-zsh"
zshCustomPath: ".config/oh-my-zsh/custom"
gitWorktreeZshPluginRepo: "https://github.com/trthomps/git-worktree-zsh-plugin.git"
gitWorktreeZshPluginPath: ".config/oh-my-zsh/custom/plugins/git-worktree"
zshTheme: ""

zshPlugins:
  - git
  - docker
  - docker-compose
  - command-not-found
  - git-worktree
  - z

workZshPlugins: []

opencodeEnabled: false
opencodeRepo: ""
opencodePath: ".config/opencode"
